image: node:14.15-stretch
#variables:
#  FF_USE_FASTZIP: "true"

#cache:
#  untracked: true
#  policy: push
#  key: ${CI_COMMIT_SHORT_SHA}
#  paths:
#    - node_modules/

#.pull_cached_node_modules:
#  cache:
#    untracked: true
#    key: ${CI_COMMIT_SHORT_SHA}
#    policy: pull

stages:
#  - setup
  - test

#install:
#  stage: setup
#  script:
#    - npm ci

test:
  stage: test
  before_script:
    - ls
    - npm install
    - npm run build --prod
  script:
    - npm -version